#pragma config(Motor,  port2,           right_front_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left_front_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           left_back_motor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           right_back_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           top_left_lift_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           bottom_left_lift_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           top_right_lift_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           bottom_right_lift_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          middle_motor,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Amy_Drive.h"
#include "Amy_Macros.h"
#include "Amy_Lift.h"

void pre_auton()
{

}

task autonomous()
{

}

task usercontrol()
{

	while(true)
	{
		updateOI();
		drive();
		lift();

	}


}
